[package]
name = "ceresdb-client-rs"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.57"
dashmap = "5.3.4"
futures = "0.3"
tonic = "0.8.1"
tokio = "1.15"
thiserror = "1.0.38"
arrow = "23.0.0"
paste = "1.0"
zstd = { version = "0.12", default-features = false }

[dependencies.ceresdbproto]
git = "https://github.com/mrrtree/ceresdbproto.git"
rev = "89e166b3077998046a4353cac82b44853de7ee74"

[dependencies.common_types]
git = "https://github.com/CeresDB/ceresdb.git"
rev = "813992230dc4fb89d314aae4a0ed0cf5f648a6e1"
default-features = false

[dev-dependencies]
chrono = "0.4"
tokio = { version = "1.15", features = ["full"] }

[lib]
name = "ceresdb_client_rs"
