[package]
name = "ceresdb-client-rs"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.57"
avro-rs = "0.13.0"
dashmap = "5.3.4"
futures = "0.3"
tonic = "0.8.1"
tokio = "1.15"

[dependencies.ceresdbproto]
git = "https://github.com/CeresDB/ceresdbproto.git"
rev = "8cd021e19e44e4bfba0c6f66fc59857c07d0737d"

[dependencies.common_types]
git = "https://github.com/CeresDB/ceresdb.git"
rev = "813992230dc4fb89d314aae4a0ed0cf5f648a6e1"
default-features = false

[dev-dependencies]
chrono = "0.4"
tokio = { version = "1.15", features = ["full"] }

[lib]
name = "ceresdb_client_rs"
