[package]
name = "ceresdb-client-rs"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.57"
avro-rs = "0.13.0"
dashmap = "5.3.4"
futures = "0.3"
tonic = "0.8.1"
tokio = "1.15"

[dependencies.ceresdbproto]
git = "https://github.com/CeresDB/ceresdbproto.git"
rev = "29cb0c6fba76401fd9a4ae5b8cacc9002ad78650"

[dependencies.common_types]
git = "https://github.com/CeresDB/ceresdb.git"
rev = "2ab4885b7d32f6c72a398af91467d2d53c5dff21"
default-features = false

[dev-dependencies]
chrono = "0.4"
tokio = { version = "1.15", features = ["full"] }

[lib]
name = "ceresdb_client_rs"
