[package]
name = "ceresdb-client-rs"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdbservice@gmail.com>"]
edition = "2021"

[dependencies]
arrow = "23.0.0"
async-trait = "0.1.57"
dashmap = "5.3.4"
futures = "0.3"
paste = "1.0"
thiserror = "1.0.38"
tokio = "1.15"
tonic = "0.8.1"
zstd = { version = "0.12", default-features = false }


[dependencies.ceresdbproto]
git = "https://github.com/CeresDB/ceresdbproto.git"
rev = "55495dd395d12a1f97f6c98e355290671d107c44"

[dev-dependencies]
chrono = "0.4"
tokio = { version = "1.15", features = ["full"] }

[lib]
name = "ceresdb_client_rs"
