# Copyright 2023 The HoraeDB Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'etc/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'etc/**'
      - '**.md'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C debuginfo=1"

jobs:
  style-check:
    name: style-check
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: Swatinem/rust-cache@v2
      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install --yes protobuf-compiler
      - name: Install cargo binaries
        run: cargo install cargo-sort
      - name: Run Style Check
        run: |
          cargo fmt --all --check
          cargo clippy --tests --all-features --all-targets --workspace -- -D warnings
          cargo sort --workspace --check

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: Swatinem/rust-cache@v2
      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install --yes protobuf-compiler
      - name: Run Test
        run: cargo test --workspace
